export const REQUEST_ALL_COUNTRIES = 'REQUEST_ALL_COUNTRIES';
export const REQUEST_ALL_COUNTRIES_SUCCEEDED = 'REQUEST_ALL_COUNTRIES_SUCCEEDED'
export const REQUEST_ALL_COUNTRIES_FAILED = 'REQUEST_ALL_COUNTRIES_FAILED'