export const REQUEST_ALL_COUNTRIES ='REQUEST_ALL_COUNTRIES';
export const REQUEST_ALL_COUNTRIES_SUCCEEDED ='REQUEST_ALL_COUNTRIES_SUCCEEDED';
export const REQUEST_ALL_COUNTRIES_FAILED ='REQUEST_ALL_COUNTRIES_FAILED';

export const REQUEST_COVID_SUMMARY = 'REQUEST_COVID_SUMMARY';
export const REQUEST_COVID_SUMMARY_SUCCEEDED = 'REQUEST_COVID_SUMMARY_SUCCEEDED';
export const REQUEST_COVID_SUMMARY_FAILED = 'REQUEST_COVID_SUMMARY_FAILED';

export const REQUEST_STATES = 'REQUEST_STATES';
export const REQUEST_STATES_SUCCEEDED = 'REQUEST_STATES_SUCCEEDED';
export const REQUEST_STATES_FAILED = 'REQUEST_STATES_FAILED';

export const SET_SELECTED_STATE = 'SET_SELECTED_STATE';
export const SET_SELECTED_STATE_SUCCEEDED = 'SET_SELECTED_STATE_SUCCEEDED';
export const SET_SELECTED_STATE_FAILED = 'SET_SELECTED_STATE_FAILED';

export const SET_SELECTED_STATE_DATA = 'SET_SELECTED_STATE_DATA';
export const SET_SELECTED_STATE_DATA_SUCCEEDED = 'SET_SELECTED_STATE_DATA_SUCCEEDED';
export const SET_SELECTED_STATE_DATA_FAILED = 'SET_SELECTED_STATE_DATA_FAILED';

export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_COUNTRY_SUCCEEDED = 'SET_SELECTED_COUNTRY_SUCCEEDED'
export const SET_SELECTED_COUNTRY_FAILED = 'SET_SELECTED_COUNTRY_FAILED'

export const SET_SELECTED_COUNTRY_DATA = 'SET_SELECTED_COUNTRY_DATA';
export const SET_SELECTED_COUNTRY_DATA_SUCCEEDED = 'SET_SELECTED_COUNTRY_DATA_SUCCEEDED';
export const SET_SELECTED_COUNTRY_DATA_FAILED = 'SET_SELECTED_COUNTRY_DATA_FAILED';