export const REQUEST_ALL_COUNTRIES ='REQUEST_ALL_COUNTRIES';
export const REQUEST_ALL_COUNTRIES_SUCCEEDED ='REQUEST_ALL_COUNTRIES_SUCCEEDED';
export const REQUEST_ALL_COUNTRIES_FAILED ='REQUEST_ALL_COUNTRIES_FAILED';

export const REQUEST_COVID_SUMMARY = 'REQUEST_COVID_SUMMARY';
export const REQUEST_COVID_SUMMARY_SUCCEEDED = 'REQUEST_COVID_SUMMARY_SUCCEEDED';
export const REQUEST_COVID_SUMMARY_FAILED = 'REQUEST_COVID_SUMMARY_FAILED';